version: '3'
services:
  api:
    container_name: rust_api
    tty: true

    environment:
      TZ: Asia/Tokyo

    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - type: bind
        source: .
        target: /home

    ports:
      - "127.0.0.1:8080:8080"